
name = "Test Package"
version = "1.2.9"
download = "https://sasmlange.github.io/jstar_package.zip"
docs = """
Test Package
===============

This package is great! Try it out. Import it by putting this in you jsr file.

'''
import jpm.testpackage.script
'''
"""
